development: 
  client_id: U5FN33ZEFSF23J2OKYTWQEUQLCRDUTNZTH0T4TDDYW3KFPZ3
  client_secret: 1DXWLXDY2YDQVXFZ5AFYNMYHRDBBVUJGIY2ZAPGJ1JSXFVUM 
test: 
  client_id: U5FN33ZEFSF23J2OKYTWQEUQLCRDUTNZTH0T4TDDYW3KFPZ3
  client_secret: 1DXWLXDY2YDQVXFZ5AFYNMYHRDBBVUJGIY2ZAPGJ1JSXFVUM
production: 
  client_id: 4IID5QNUA3FSAKWXCVLHDOH0DFBW2W2ZF1IBKQUIPQ2JGZ5N
  client_secret: GB5BRFZHCCLUEX5MA4SQH4QED4BA55DBCJ3VKWUXJRB12LSO